spring:
  application:
    name: spring-redis-poc
  data:
    redis:
      # NOTA: Configuração dinâmica via Parameter Store
      # Prioridade: Parameter Store > Environment Variables > Default
      # Parameter Store: /poc/redis/endpoint e /poc/redis/port
      host: ${/poc/redis/endpoint:poc-redis-01ndkd.serverless.use1.cache.amazonaws.com}
      port: ${/poc/redis/port:6379}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
          max-wait: 2000ms
        shutdown-timeout: 100ms
  session:
    store-type: redis
    redis:
      namespace: "poc:session"
      flush-mode: on_save
    timeout: 30m
  cloud:
    aws:
      parameterstore:
        enabled: true
        prefix: /poc

server:
  port: 8080
  servlet:
    session:
      timeout: 30m
  # Headers anti-cache globais
  forward-headers-strategy: framework

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      cors:
        allowed-origins: "*"
        allowed-methods: GET,POST,PUT,DELETE,OPTIONS
        allowed-headers: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      cloudwatch:
        enabled: true
        namespace: POC/SpringRedis
        step: 1m

logging:
  level:
    com.poc: INFO
    org.springframework.session: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%X{traceId}] %logger{36} - %msg%n"

# Configurações customizadas para POC
poc:
  cache:
    # Estratégias anti-cache habilitadas
    anti-cache-enabled: true
    # Headers anti-cache padrão
    default-headers:
      - "Cache-Control: no-cache, no-store, must-revalidate"
      - "Pragma: no-cache"
      - "Expires: 0"
