spring:
  redis:
    host: ${/poc/redis/endpoint}
    port: ${/poc/redis/port}
    ssl: ${/poc/redis/ssl}
    timeout: ${/poc/redis/timeout:2000}ms
    jedis:
      pool:
        max-active: ${/poc/redis/pool/max-active:8}
        max-idle: ${/poc/redis/pool/max-active:8}
        min-idle: ${/poc/redis/pool/min-idle:4}
        max-wait: 1000ms
        test-on-borrow: true
        test-on-return: false
        test-while-idle: true
        time-between-eviction-runs: 30000ms
