spring:
  application:
    name: spring-redis-poc
  
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  
  session:
    store-type: redis
    redis:
      namespace: "poc:session"
      flush-mode: on_save
    timeout: 30m

server:
  port: 8080
  servlet:
    session:
      timeout: 30m
  # Headers anti-cache globais
  forward-headers-strategy: framework

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,circuitbreakers,ratelimiters
      cors:
        allowed-origins: "*"
        allowed-methods: GET,POST,PUT,DELETE,OPTIONS
        allowed-headers: "*"
  endpoint:
    health:
      show-details: always
    circuitbreakers:
      enabled: true
  metrics:
    export:
      cloudwatch:
        enabled: true
        namespace: POC/SpringRedis
        step: 1m
    distribution:
      percentiles-histogram:
        resilience4j.circuitbreaker.calls: true

logging:
  level:
    com.poc: INFO
    org.springframework.session: DEBUG
    org.springframework.web: DEBUG
    io.github.resilience4j: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%X{traceId}] %logger{36} - %msg%n"

# Resilience4j Circuit Breaker Configuration
resilience4j:
  circuitbreaker:
    instances:
      redis-service:
        failure-rate-threshold: 50                    # 50% de falhas para abrir
        minimum-number-of-calls: 10                   # Mínimo 10 calls para avaliar
        wait-duration-in-open-state: 30s              # Espera 30s antes de testar
        sliding-window-size: 20                       # Janela de 20 calls
        permitted-number-of-calls-in-half-open-state: 3  # 3 calls para testar recuperação
        sliding-window-type: COUNT_BASED              # Baseado em contagem
        automatic-transition-from-open-to-half-open-enabled: true
        record-exceptions:
          - org.springframework.data.redis.RedisConnectionFailureException
          - org.springframework.data.redis.RedisSystemException
          - java.util.concurrent.TimeoutException
  
  ratelimiter:
    instances:
      api-limiter:
        limit-for-period: 100                         # 100 requests por período
        limit-refresh-period: 1s                      # Período de 1 segundo
        timeout-duration: 0s                          # Sem espera, rejeita imediatamente
  
  retry:
    instances:
      redis-retry:
        max-attempts: 3                               # Máximo 3 tentativas
        wait-duration: 500ms                          # Espera 500ms entre tentativas
        retry-exceptions:
          - org.springframework.data.redis.RedisConnectionFailureException

# Configurações customizadas para POC
poc:
  cache:
    # Estratégias anti-cache habilitadas
    anti-cache-enabled: true
    # Headers anti-cache padrão
    default-headers:
      - "Cache-Control: no-cache, no-store, must-revalidate"
      - "Pragma: no-cache"
      - "Expires: 0"
